name: 'set up unittests'
description: 'downloads and installs R packages and system dependencies. Only works for Windows and macOS'
inputs:
  requiresJAGS:
    description: 'Should JAGS be available?'
    required: false
    default: false

runs:
  using: "composite"
  steps:

# TODO (27-11-2020)
# Composite steps don't allow if statements yet but will in the future (see https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#if-condition)
# Once those are supported, we should probably use those instead of having if statements in bash & R. They're still commented out at the moment.
#

    - name: Install system dependencies on macOS
      # if: runner.os == 'macOS'
      run: |
        if [ "${{ runner.os }}" = 'macOS' ]; then
          brew cask install xquartz
        fi
      shell: bash

    - name: Clone jasp-required-files
      run: |
        if [ "${{ runner.os }}" = 'macOS' ]; then
          branch='MacOS-Original'
        else
          branch='Windows'
        fi
        echo "branch=$branch"
        git clone --branch=$branch https://github.com/jasp-stats/jasp-required-files.git pkgs
      working-directory: ..
      shell: bash

    - name: Set R library path
      run: |
        libPath <- if (.Platform$OS.type == "windows") "/R/library" else "/Frameworks/R.framework/Versions/3.6/Resources/library/"
        path <- normalizePath(file.path("..", "pkgs", libPath), winslash = "/")
        cat("\n.libPaths(c('", path, "', .libPaths()))\n", file = "~/.Rprofile", sep = "", append = TRUE)
      shell: Rscript {0}

    - name: Install JAGS on macOS
      # if: inputs.needsJAGS && runner.os == 'macOS'
      run: |
        if [ "${{ inputs.needsJAGS }}" = 'true' ] && [ "${{ runner.os }}" = 'macOS' ]; then
          rm '/usr/local/bin/gfortran'
          brew install jags
        fi
      shell: bash

    - name: Locate JAGS on Windows
      # if: inputs.needsJAGS && runner.os == 'Windows'
      run: |
        if (.Platform$OS.type == "windows" && "${{ inputs.needsJAGS }}" == "true") {
          path <- normalizePath(file.path("..", "pkgs", "64", "JAGS"), winslash = "/")
          cat("\nSys.setenv(JAGS_HOME = '", path, "')\n", file = "~/.Rprofile", sep = "", append = TRUE)
        }
      shell: Rscript {0}

    - name: Setup jaspTools
      run: |
        install.packages("remotes")
        remotes::install_github("jasp-stats/jaspTools")
        jaspTools::setupJaspTools()
      shell: Rscript {0}

